window.HRMS_SEED = {
  company: {
    name: "SKYLINX PeopleOS",
    legalName: "SKYLINX HR Private Limited",
    locations: ["Mumbai", "Bengaluru", "Delhi", "Hyderabad", "Pune"],
    payrollMonth: "May 2026",
    workWeek: "Monday to Saturday",
  },
  panels: [
    { id: "PAN-1", name: "Super Admin Panel", users: 1, status: "active", focus: "Company, license, audit, backup and SaaS controls" },
    { id: "PAN-2", name: "HR/Admin Panel", users: 4, status: "active", focus: "Employees, attendance, leave, payroll and reports" },
    { id: "PAN-3", name: "Manager Panel", users: 8, status: "active", focus: "Team approvals, attendance, leave and expenses" },
    { id: "PAN-4", name: "Employee Self-Service Panel", users: 142, status: "active", focus: "Profile, attendance, leave, payslips and documents" },
  ],
  modules: [
    { id: "MOD-1", name: "Authentication", phase: "MVP", status: "ready", owner: "Platform", items: ["Login", "OTP Login", "Forgot Password", "Role-Based Access", "User Permissions"] },
    { id: "MOD-2", name: "Dashboard", phase: "MVP", status: "ready", owner: "HR", items: ["Employee Count", "Attendance Summary", "Leave Summary", "Payroll Summary", "Quick Actions"] },
    { id: "MOD-3", name: "Employee Directory", phase: "MVP", status: "ready", owner: "HR", items: ["Employee List", "Add Employee", "Bulk Upload", "Profile", "Documents", "Bank Details", "Verification"] },
    { id: "MOD-4", name: "Attendance Management", phase: "MVP", status: "ready", owner: "Operations", items: ["Logs", "Check-In / Check-Out", "Shifts", "Late Mark Rules", "Regularization", "Overtime", "Geo Attendance"] },
    { id: "MOD-5", name: "Leave Management", phase: "MVP", status: "ready", owner: "HR", items: ["Apply Leave", "Approvals", "Balance", "Leave Types", "Carry Forward", "Sandwich Leave", "Reports"] },
    { id: "MOD-6", name: "Payroll Management", phase: "MVP", status: "ready", owner: "Finance", items: ["Salary Structure", "Payroll Run", "Payslips", "Deductions", "PF / ESI / PT", "TDS", "Bank Export"] },
    { id: "MOD-7", name: "Reports", phase: "MVP", status: "ready", owner: "Leadership", items: ["Employee Reports", "Attendance Reports", "Leave Reports", "Payroll Reports", "Excel / PDF Export"] },
    { id: "MOD-8", name: "Holiday Calendar", phase: "V2", status: "planned", owner: "HR", items: ["Mandatory Holidays", "Optional Holidays", "Regional Holidays", "Calendar View"] },
    { id: "MOD-9", name: "Organization Chart", phase: "V2", status: "planned", owner: "HR", items: ["Reporting Hierarchy", "Department Tree", "Manager Mapping"] },
    { id: "MOD-10", name: "Expense Management", phase: "V2", status: "planned", owner: "Finance", items: ["Claims", "Receipt Upload", "Manager Approval", "HR Approval", "Reimbursement"] },
    { id: "MOD-11", name: "Insurance Management", phase: "V2", status: "planned", owner: "HR", items: ["Employee Insurance", "Dependents", "Policy Details", "Claims"] },
    { id: "MOD-12", name: "ID & Visiting Card", phase: "V2", status: "planned", owner: "Admin", items: ["ID Card Template", "Visiting Card Template", "QR Code", "PDF Download"] },
    { id: "MOD-13", name: "Internal Social Feed", phase: "V2", status: "planned", owner: "HR", items: ["Announcements", "Employee Posts", "Likes", "Comments", "Birthday Wishes"] },
    { id: "MOD-14", name: "Rewards & Benefits", phase: "V3", status: "planned", owner: "HR", items: ["Vouchers", "Reward Points", "Recognition", "Benefits Marketplace"] },
    { id: "MOD-15", name: "Settings", phase: "MVP", status: "ready", owner: "Admin", items: ["Company Profile", "Departments", "Roles & Permissions", "Payroll Settings", "Attendance Settings", "Leave Settings"] },
    { id: "MOD-16", name: "Recruitment ATS", phase: "V2", status: "planned", owner: "Talent", items: ["Job Posting", "Candidate Database", "Resume Upload", "Interview Scheduling", "Walk-In", "Campus Drive", "Offer Letter"] },
  ],
  security: [
    { id: "SEC-1", name: "2FA / OTP", status: "planned", priority: "high" },
    { id: "SEC-2", name: "Audit logs", status: "ready", priority: "high" },
    { id: "SEC-3", name: "Data backup", status: "planned", priority: "high" },
    { id: "SEC-4", name: "Role permissions", status: "ready", priority: "high" },
    { id: "SEC-5", name: "Payroll data encryption", status: "planned", priority: "critical" },
    { id: "SEC-6", name: "Employee document security", status: "planned", priority: "critical" },
  ],
  notifications: [
    { id: "NOT-1", name: "Email alerts", status: "planned", channel: "Email" },
    { id: "NOT-2", name: "WhatsApp alerts", status: "planned", channel: "WhatsApp" },
    { id: "NOT-3", name: "Leave approval alerts", status: "ready", channel: "Email" },
    { id: "NOT-4", name: "Attendance reminders", status: "planned", channel: "Email + WhatsApp" },
    { id: "NOT-5", name: "Payroll/payslip alerts", status: "planned", channel: "Email" },
  ],
  backups: [
    { id: "BKP-1", name: "Daily database backup", status: "planned", frequency: "Daily" },
    { id: "BKP-2", name: "File backup", status: "planned", frequency: "Daily" },
    { id: "BKP-3", name: "Restore option", status: "planned", frequency: "On demand" },
    { id: "BKP-4", name: "Disaster recovery plan", status: "planned", frequency: "Quarterly drill" },
  ],
  settingsCatalog: [
    { id: "SET-1", name: "Company branding", status: "ready" },
    { id: "SET-2", name: "Module enable/disable", status: "planned" },
    { id: "SET-3", name: "User activity tracking", status: "ready" },
    { id: "SET-4", name: "Data import/export", status: "planned" },
    { id: "SET-5", name: "Subscription/license control", status: "planned" },
  ],
  employees: [
    {
      id: "EMP-1001",
      name: "Aarav Mehta",
      role: "HR Manager",
      department: "People",
      location: "Mumbai",
      email: "aarav.mehta@peopleops.local",
      phone: "+91 98765 41001",
      joiningDate: "2021-04-12",
      salary: 1450000,
      status: "active",
    },
    {
      id: "EMP-1002",
      name: "Priya Nair",
      role: "Payroll Specialist",
      department: "Finance",
      location: "Bengaluru",
      email: "priya.nair@peopleops.local",
      phone: "+91 98765 41002",
      joiningDate: "2022-08-01",
      salary: 980000,
      status: "active",
    },
    {
      id: "EMP-1003",
      name: "Kabir Sethi",
      role: "Frontend Engineer",
      department: "Engineering",
      location: "Delhi",
      email: "kabir.sethi@peopleops.local",
      phone: "+91 98765 41003",
      joiningDate: "2023-01-16",
      salary: 1680000,
      status: "active",
    },
    {
      id: "EMP-1004",
      name: "Sara Khan",
      role: "Sales Executive",
      department: "Sales",
      location: "Hyderabad",
      email: "sara.khan@peopleops.local",
      phone: "+91 98765 41004",
      joiningDate: "2023-09-04",
      salary: 820000,
      status: "active",
    },
    {
      id: "EMP-1005",
      name: "Rohan Iyer",
      role: "Operations Lead",
      department: "Operations",
      location: "Pune",
      email: "rohan.iyer@peopleops.local",
      phone: "+91 98765 41005",
      joiningDate: "2020-11-23",
      salary: 1320000,
      status: "inactive",
    },
  ],
  onboarding: [
    { id: "ONB-1", employeeId: "EMP-1004", stage: "Document Collection", progress: 65, owner: "Aarav Mehta", due: "2026-05-30" },
    { id: "ONB-2", employeeId: "EMP-1003", stage: "Asset Allocation", progress: 80, owner: "Priya Nair", due: "2026-05-27" },
    { id: "ONB-3", employeeId: "EMP-1002", stage: "Policy Acknowledgement", progress: 100, owner: "Aarav Mehta", due: "2026-05-24" },
  ],
  documents: [
    { id: "DOC-1", name: "Aadhaar", employeeId: "EMP-1001", status: "verified", expires: "" },
    { id: "DOC-2", name: "PAN", employeeId: "EMP-1002", status: "verified", expires: "" },
    { id: "DOC-3", name: "Bank Proof", employeeId: "EMP-1003", status: "pending", expires: "" },
    { id: "DOC-4", name: "Employment Agreement", employeeId: "EMP-1004", status: "pending", expires: "2026-06-05" },
  ],
  compliance: [
    { id: "COM-1", name: "PF challan", period: "May 2026", due: "2026-06-15", status: "pending" },
    { id: "COM-2", name: "ESI filing", period: "May 2026", due: "2026-06-21", status: "pending" },
    { id: "COM-3", name: "Professional Tax", period: "May 2026", due: "2026-06-10", status: "approved" },
    { id: "COM-4", name: "TDS deposit", period: "May 2026", due: "2026-06-07", status: "pending" },
  ],
  announcements: [
    { id: "ANN-1", title: "May payroll verification closes today", audience: "HR and Finance", date: "2026-05-25" },
    { id: "ANN-2", title: "Saturday shift roster published", audience: "All employees", date: "2026-05-24" },
  ],
  attendance: [
    { id: "ATT-1", employeeId: "EMP-1001", date: "2026-05-25", checkIn: "09:12", checkOut: "18:18", status: "present" },
    { id: "ATT-2", employeeId: "EMP-1002", date: "2026-05-25", checkIn: "09:48", checkOut: "18:05", status: "late" },
    { id: "ATT-3", employeeId: "EMP-1003", date: "2026-05-25", checkIn: "09:06", checkOut: "18:31", status: "present" },
    { id: "ATT-4", employeeId: "EMP-1004", date: "2026-05-25", checkIn: "", checkOut: "", status: "absent" },
  ],
  leaveRequests: [
    { id: "LEA-1", employeeId: "EMP-1003", type: "Casual Leave", from: "2026-05-28", to: "2026-05-29", days: 2, status: "pending", reason: "Family function" },
    { id: "LEA-2", employeeId: "EMP-1002", type: "Sick Leave", from: "2026-05-20", to: "2026-05-20", days: 1, status: "approved", reason: "Medical appointment" },
    { id: "LEA-3", employeeId: "EMP-1004", type: "Earned Leave", from: "2026-06-10", to: "2026-06-14", days: 5, status: "pending", reason: "Travel" },
  ],
  payroll: [
    { id: "PAY-1", employeeId: "EMP-1001", month: "May 2026", gross: 120833, deductions: 16800, net: 104033, status: "paid" },
    { id: "PAY-2", employeeId: "EMP-1002", month: "May 2026", gross: 81667, deductions: 9200, net: 72467, status: "paid" },
    { id: "PAY-3", employeeId: "EMP-1003", month: "May 2026", gross: 140000, deductions: 21600, net: 118400, status: "draft" },
    { id: "PAY-4", employeeId: "EMP-1004", month: "May 2026", gross: 68333, deductions: 6900, net: 61433, status: "hold" },
  ],
  jobs: [
    { id: "JOB-1", title: "Backend Engineer", department: "Engineering", stage: "Interview", candidates: 12 },
    { id: "JOB-2", title: "HR Executive", department: "People", stage: "Screening", candidates: 28 },
    { id: "JOB-3", title: "Accountant", department: "Finance", stage: "Offer", candidates: 5 },
  ],
};
